---
title: "Word2vec on Ebony and Black World/Negro Digest"
author: "Kushal K Dey"
date: "4/11/2018"
output: html_document
---

```{r}
library(wordVectors)
```

## Introduction

We combine text data for every year of the issues of Black World/Negro Digest and
Ebony and then run word2vec on the combined text data.

The text data contains the following bi-grams



```{r}
## civil rights bigram
## black power
## black panther
## martin luther king
## malcolm x
## dr king
```



## Prepping the data

### Black World / Negro Digest

```{r echo=TRUE, eval=FALSE}
out <- prep_word2vec(origin = "../Negro_Digest/ND_1961/", 
                     destination = "../Negro_Digest/ND_1961/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1962/", 
                     destination = "../Negro_Digest/ND_1962/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1963/", 
                     destination = "../Negro_Digest/ND_1963/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1964/", 
                     destination = "../Negro_Digest/ND_1964/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1965/", 
                     destination = "../Negro_Digest/ND_1965/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1966/", 
                     destination = "../Negro_Digest/ND_1966/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1967/", 
                     destination = "../Negro_Digest/ND_1967/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1968/", 
                     destination = "../Negro_Digest/ND_1968/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1969/", 
                     destination = "../Negro_Digest/ND_1969/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Negro_Digest/ND_1970/", 
                     destination = "../Negro_Digest/ND_1970/pooled.txt", lowercase = T)


out <- prep_word2vec(origin = "../Black_World/BL_1970/", 
                     destination = "../Black_World/BL_1970/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1971/", 
                     destination = "../Black_World/BL_1971/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1972/", 
                     destination = "../Black_World/BL_1972/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1973/",
                     destination = "../Black_World/BL_1973/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1974/", 
                     destination = "../Black_World/BL_1974/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1975/", 
                     destination = "../Black_World/BL_1975/pooled.txt", lowercase = T)
out <- prep_word2vec(origin = "../Black_World/BL_1976/", 
                     destination = "../Black_World/BL_1976/pooled.txt", lowercase = T)

```

### Ebony

```{r echo=TRUE, eval=FALSE}
dirs <- c("../Ebony/1961/", "../Ebony/1962/", "../Ebony/1963/",
          "../Ebony/1964/", "../Ebony/1965/", "../Ebony/1966/",
          "../Ebony/1967/", "../Ebony/1968/", "../Ebony/1969/",
          "../Ebony/1970/", "../Ebony/1971/", "../Ebony/1972/",
          "../Ebony/1973/", "../Ebony/1974/", "../Ebony/1975/",
          "../Ebony/1976/")

library(wordVectors)
for(m in 1:length(dirs)){
  out <- prep_word2vec(origin = dirs[m], destination = paste0(dirs[m],"pooled.txt"), lowercase = T)
}
```

## word2vec model

### Black World/ Negro Digest

```{r echo=TRUE, eval=FALSE}
dirs <- c("../Negro_Digest/ND_1961/",
          "../Negro_Digest/ND_1962/",
          "../Negro_Digest/ND_1963/",
          "../Negro_Digest/ND_1964/",
          "../Negro_Digest/ND_1965/",
          "../Negro_Digest/ND_1966/",
          "../Negro_Digest/ND_1967/",
          "../Negro_Digest/ND_1968/",
          "../Negro_Digest/ND_1969/",
          "../Negro_Digest/ND_1970/",
          "../Black_World/BL_1970/",
          "../Black_World/BL_1971/",
          "../Black_World/BL_1972/",
          "../Black_World/BL_1973/",
          "../Black_World/BL_1974/",
          "../Black_World/BL_1975/",
          "../Black_World/BL_1976/")

for(m in 1:length(dirs)){
  model = train_word2vec(paste0(dirs[m], "pooled.txt"),
                         paste0(dirs[m], "pooled_word2vec.bin"),
                         vectors=100,threads=10,window=10,
                         iter=30, min_count = 3, negative_samples=0, 
                         force = TRUE)
}


```

### Ebony

```{r echo=TRUE, eval=FALSE}
dirs <- c("../Ebony/1961/", "../Ebony/1962/", "../Ebony/1963/",
          "../Ebony/1964/", "../Ebony/1965/", "../Ebony/1966/",
          "../Ebony/1967/", "../Ebony/1968/", "../Ebony/1969/",
          "../Ebony/1970/", "../Ebony/1971/", "../Ebony/1972/",
          "../Ebony/1973/", "../Ebony/1974/", "../Ebony/1975/",
          "../Ebony/1976/")

## civil rights bigram
## black power
## black panther
## martin luther king
## malcolm x
## dr king


for(m in 1:length(dirs)){
    model = train_word2vec(paste0(dirs[m], "pooled.txt"),
                           paste0(dirs[m], "pooled_word2vec.bin"),
                           vectors=100,threads=10,window=10,
                           iter=30, min_count = 3, negative_samples=0, 
                           force = TRUE)
}

```



