---
title: "word2vec model on [Black, Negro] Identity texts"
author: "Kushal K Dey"
date: "4/12/2018"
output: html_document
---

We fit the word2vec model on the text data from the identity neutralized texts 
from Ebony and Black world/Negro Digest where the terms negro and negroes are
converted to black and blacks respectively.

## Black World/ Negro Digest

```{r echo=TRUE, eval=FALSE}
dir <- "../BL_ND_ID/"
ll <- list.files(dir, pattern = '.txt')
for(m in 1:length(ll)){
  model = train_word2vec(paste0(dir, ll[m]),
                         paste0(dir, ll[m], ".bin"),
                         vectors=100,threads=10,window=10,
                         iter=30, min_count = 3, negative_samples=0, 
                         force = TRUE)
}

```

## Ebony

```{r echo=TRUE, eval=FALSE}
dir <- "../Ebony_ID/"
ll <- list.files(dir, pattern = ".txt")
for(m in 1:length(ll)){
  model = train_word2vec(paste0(dir, ll[m]),
                         paste0(dir, ll[m], ".bin"),
                         vectors=100,threads=10,window=10,
                         iter=30, min_count = 3, negative_samples=0, 
                         force = TRUE)
}

```

## SessionInfo

```{r}
sessionInfo()
```

